name: dante
description: a simple logger for your flutter apps, inspired by the best poetrydartdoc Dante
version: 0.0.4
homepage: https://github.com/dbbd59/dante

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  ficcanaso: ^2.0.7
  test: ^1.17.12
